name: UAP Reporting CI
on:
  push:
    branches: [development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compilar aplicação
        run: echo Compilando aplicação #somente exemplo
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ${{ vars.URL }}
    needs: build
    steps:
      - name: Baixando arquivos na Hostinger // Checkout - [Development]
        uses: actions/checkout@v1
      - name: Deploy in production - Hostinger
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          #SOURCE: "/" #Repository folder code
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }} #folder on server
      - name: Executando comandos SSH - Laravel // Hostinger [DEV]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.APPLEBOY_SSH_PRIVATE_KEY_ED25519 }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd ${{ vars.TARGET }}
            (php artisan down) || true
            php artisan migrate
            php artisan db:seed
            php artisan up
            echo "Aplication updated!"