name: UAP Reporting CI
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando arquivos - Hostinger
        uses: actions/checkout@v4
      - name: Deploy in production - Hostinger
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          #SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}
      - name: Executando comandos SSH / Laravel - Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: "cd ${{ secrets.TARGET }} && ./laravel-deploy.sh"
