name: UAP Reporting CI
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UAP Reporting
        uses: actions/checkout@v2
      - name: Deploy in production - Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: "cd /home/u744666870/domains/uapreporting.space && ./laravel-deploy.sh"